name: Package and Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            !node_modules/.cache
          key: node-modules-${{ hashFiles('package.json', 'package-lock.json') }}

      - name: Install Modules
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Use the Release Tag Version
        run: |
          npm version from-git --allow-same-version --no-git-tag-version

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build the package
        run: npm pack

      - name: Upload the package tgz as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: '*.tgz'

      - name: NPM registry authentication
        run: npm set //registry.npmjs.org/:_authToken ${{ secrets.NPMJSORG_PUBLISH_TOKEN }}

      - name: Publish the package
        run: |
          npm publish --access public --ignore-scripts
