name: Package and Publish

on:
  release:
    types: [published]

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/configure-nodejs
        with:
          lookup-only: 'true' # We only want to lookup from the cache - if a hit, this job does nothing

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/configure-nodejs

      - name: Use the Release Tag Version
        run: |
          npm version from-git --allow-same-version --no-git-tag-version

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build the package
        run: npm pack

      - name: Upload the package tgz as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: '*.tgz'

      - name: NPM registry authentication
        run: npm set //registry.npmjs.org/:_authToken ${{ secrets.NPMJSORG_PUBLISH_TOKEN }}

      - name: Publish the package
        run: |
          npm publish --access public --ignore-scripts
